// This file is auto-generated by tauri-specta on app startup (debug builds only).
// Do not edit manually — run `pnpm tauri dev` to regenerate.

import { invoke as TAURI_INVOKE } from '@tauri-apps/api/core';

export type Transaction = {
  id: number;
  date: string;
  description: string;
  amount: number;
  accounted: boolean;
};

export type Filter = {
  id: number;
  name: string;
  pattern: string;
};

export type ImportResult = {
  imported: number;
};

export type ReportRow = {
  filterName: string;
  lastDate: string;
  totalAmount: number;
  transactions: Transaction[];
};

export type ReportOutput = {
  rows: ReportRow[];
  text: string;
};

export const commands = {
  async importTransactions(paths: string[]): Promise<ImportResult> {
    return await TAURI_INVOKE('import_transactions', { paths });
  },

  async listTransactions(dateFrom: string | null, dateTo: string | null): Promise<Transaction[]> {
    return await TAURI_INVOKE('list_transactions', { dateFrom, dateTo });
  },

  async listFilters(): Promise<Filter[]> {
    return await TAURI_INVOKE('list_filters');
  },

  async createFilter(name: string, pattern: string): Promise<Filter> {
    return await TAURI_INVOKE('create_filter', { name, pattern });
  },

  async updateFilter(id: number, name: string, pattern: string): Promise<Filter> {
    return await TAURI_INVOKE('update_filter', { id, name, pattern });
  },

  async deleteFilter(id: number): Promise<void> {
    await TAURI_INVOKE('delete_filter', { id });
  },

  async generateReport(dateFrom: string | null, dateTo: string | null): Promise<ReportOutput> {
    return await TAURI_INVOKE('generate_report', { dateFrom, dateTo });
  },
};
