
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
/**
 * Parse CSV files and detect potential duplicates against existing DB rows.
 * Does NOT insert anything — the frontend confirms which rows to keep.
 */
async previewImport(paths: string[]) : Promise<Result<PreviewResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("preview_import", { paths }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Insert the transactions the user confirmed (i.e. not marked as duplicates).
 */
async confirmImport(transactions: PendingTransaction[]) : Promise<Result<ImportResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("confirm_import", { transactions }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listTransactions(dateFrom: string | null, dateTo: string | null) : Promise<Result<Transaction[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_transactions", { dateFrom, dateTo }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listFilters() : Promise<Result<Filter[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_filters") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createFilter(name: string, pattern: string) : Promise<Result<Filter, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_filter", { name, pattern }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateFilter(id: number, name: string, pattern: string) : Promise<Result<Filter, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_filter", { id, name, pattern }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteFilter(id: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_filter", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async generateReport(dateFrom: string | null, dateTo: string | null) : Promise<Result<ReportOutput, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("generate_report", { dateFrom, dateTo }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getSplitCount() : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_split_count") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setSplitCount(count: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_split_count", { count }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async exportDb(path: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("export_db", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async importDb(path: string) : Promise<Result<ImportDbResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("import_db", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type Filter = { id: number; name: string; pattern: string }
export type ImportDbResult = { transactions: number; filters: number; settings: number }
export type ImportResult = { imported: number }
/**
 * A parsed transaction returned to the frontend for user review before insertion.
 */
export type PendingTransaction = { date: string; description: string; amount: number; is_possible_duplicate: boolean }
export type PreviewResult = { transactions: PendingTransaction[] }
export type ReportOutput = { rows: ReportRow[]; text: string }
export type ReportRow = { filter_name: string; last_date: string; total_amount: number; transactions: Transaction[] }
export type Transaction = { id: number; date: string; description: string; amount: number; accounted: boolean }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
